Hw11 telnet client
vitermakov/otusgo-hw pull request #10
Opened 2022-12-13 15:53 UTC by vitermakov

## Домашнее задание №11 «Клиент TELNET»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2022-12-13 16:04 UTC, dshemin requested changes

2022-12-13 16:04 UTC, dshemin commented on hw11_telnet_client/main.go
> +	<-ctx.Done()
Критично:

Мы не дожидаемся завершение процессов, которые запущены в `manageProcess`. Стоит дожидаться пока они завершаться.

2022-12-13 16:04 UTC, dshemin commented on hw11_telnet_client/main.go
> +		client.Close()
Совет:

Мы передаём в эту функцию ctx и client только для того, чтобы сделать логику, которую мы вполне можем сделать в вызывающем коде.

2022-12-13 16:04 UTC, dshemin commented on hw11_telnet_client/main.go
> +	address := fmt.Sprintf("%s:%d", args[0], port)
Совет:

Обратите внимание на подсказки в конце задания.

2022-12-13 16:04 UTC, dshemin commented on hw11_telnet_client/main.go
> +	ctx, cancel := signal.NotifyContext(context.TODO(), os.Interrupt)
Совет:

Принято использовать `context.Background`.

2023-03-04 00:17 UTC, vitermakov commented on hw11_telnet_client/main.go
> +	address := fmt.Sprintf("%s:%d", args[0], port)
ввел net.JoinHostPort

2023-03-04 00:18 UTC, vitermakov commented on hw11_telnet_client/main.go
> +	ctx, cancel := signal.NotifyContext(context.TODO(), os.Interrupt)
убрал, слушаю только сигналы

2023-03-04 00:18 UTC, vitermakov commented on hw11_telnet_client/main.go
> +		client.Close()
убрал вообще manageProcess

2023-03-04 00:19 UTC, vitermakov commented on hw11_telnet_client/main.go
> +	<-ctx.Done()
убрал вообще manageProcess, дожидаюсь в случаях, кроме syscall.SIGINT. Там os.Exit. В остальных случаях будет дожидаться завершения процессов чтения/отправки

2023-03-04 06:50 UTC, dshemin approved these changes

2023-03-04 10:09 UTC, merged