Hw12 calendar
vitermakov/otusgo-hw pull request #12
Opened 2022-12-21 21:20 UTC by vitermakov

## Домашнее задание №12 «Заготовка сервиса Календарь»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Понятность и чистота кода (включая факт, что проект разбит
на пакеты по определенной логике) - до 2 баллов
- [ ] Реализовано конфигурирование сервиса - 1 балл
- [ ] Используется логгер и он настраивается из конфига - 1 балл
- [ ] Запускается простой HTTP-сервер, мидлвара удовлетворяет ТЗ - 1 балл
- [ ] Присутствуют юнит-тесты - 1 балл

Реализовано хранилище:
- [ ] in-memory - 1 балл
- [ ] sql + миграции - 2 балла

#### Зачёт от 7 баллов

# Комментарии
Разрабатываемое приложение я немного расширил, чтобы была возможность поработать 
с разными аспектами разработки на GO и позадавать вопросы, так как есть вещи, где я в раздумьях и хотел бы узнать ваше мнение.

### «Точка входа», запускающая сервис

1. В соответствии с каким-то из предложенных в ДЗ к изучению заготовок я разделил код на внутренний [/internal/](https://github.com/vitermakov/otusgo-hw/tree/hw12_calendar/hw12_13_14_15_calendar/internal), свойственный конкретному проекту и тот, которые можно таскать из проекта в проект [pkg/](https://github.com/vitermakov/otusgo-hw/tree/hw12_calendar/hw12_13_14_15_calendar/pkg).

2. Процесс [запуска приложения](https://github.com/vitermakov/otusgo-hw/blob/hw12_calendar/hw12_13_14_15_calendar/internal/app/app.go) состоит из 
    - инициализации `initialize`, где инициализируются ресурсы внешних систем (пока только БД, но туда же добавится RabbitMQ), и инициализируются [зависимости приложения - deps.go](https://github.com/vitermakov/otusgo-hw/blob/hw12_calendar/hw12_13_14_15_calendar/internal/app/deps.go). 
    - запуска процесса `run`, где будут запукаться все рабочие процессы 
    - и функции очистки `close` после выхода из приложения

3. Приложение 
    - содержит данные в [моделях](https://github.com/vitermakov/otusgo-hw/tree/hw12_calendar/hw12_13_14_15_calendar/internal/model)
    - бизнес-логика содержится [в сервисах](https://github.com/vitermakov/otusgo-hw/tree/hw12_calendar/hw12_13_14_15_calendar/internal/service)
    - для управления этими моделями в хранилищах выделяю [репозитории](https://github.com/vitermakov/otusgo-hw/tree/hw12_calendar/hw12_13_14_15_calendar/internal/repository)
    - между представительским сервисами (http, grpc, rabbit) и сервисами бизнес логики будет еще слой последника-адаптера handler (или controller)

### Конфигурирование сервиса

Тут вопров нет, [сделал ее в формате JSON](https://github.com/vitermakov/otusgo-hw/blob/hw12_calendar/hw12_13_14_15_calendar/internal/app/config/config.go), не использую внешних библиотек.

### Логирование в сервисе

Вынес в пакет [`pkg/logger`](https://github.com/vitermakov/otusgo-hw/tree/hw12_calendar/hw12_13_14_15_calendar/pkg/logger), снабдил [интерфейсом](https://github.com/vitermakov/otusgo-hw/blob/hw12_calendar/hw12_13_14_15_calendar/pkg/logger/logger.go), реализация на основе [логрус](https://github.com/vitermakov/otusgo-hw/blob/hw12_calendar/hw12_13_14_15_calendar/pkg/logger/logrus.go), есть [тесты](https://github.com/vitermakov/otusgo-hw/blob/hw12_calendar/hw12_13_14_15_calendar/pkg/logger/logger_test.go). 

### Работа с хранилищем

Я добавил еще одну модель user чтобы поработать со связью между объектами. Объект Event содержит ссылку Owner на на User. Работа с хранилищем (без учета какой-либо логики) идет через объекты репозитории. В моделях выделил отдельно модели для создания, обновления и поиска сущностей.
Бизнес логика реализована в сервисах. Все связи - через интерфейсы. Тесты есть пока только на репозитории [in-memory](https://github.com/vitermakov/otusgo-hw/tree/hw12_calendar/hw12_13_14_15_calendar/internal/repository/memory). [Миграции](https://github.com/vitermakov/otusgo-hw/tree/hw12_calendar/hw12_13_14_15_calendar/migrations) через goose.

Тут два затруднения:

1. как правильно работают с такими объектами, чтобы при расширении проекта не было проблем.
- нужно ли выделять чистые сущности без связей, как аналог записи в БД, ну т.е. где вместо Owner будет OwnerId, как это храниться в БД? А уже задействованные объекты со связями объединять в агрегаты? и получается репозитории должны будут управлять именно агрегатами. 

Ну т.е. представим, что есть Event c Owner, все поля могут быть в разных языках, к событию могут быть прикреплены файлы, как-то так:
```
Event {
    ID uuid
    Name []Lang.Value {
        {
            LangCode: 'ru',
            Value 'Добро пожаловать'
        }, {
            LangCode: 'en',
            Value 'Welcome'
        }, 
    },
    Owner User,
    Images []File,
    ......
}
```

и где-то, например при запросе списка событий все эти данные не нужны, нужно только название и дата. Где-то нужно выбрать все поля. 

Направьте пожалуйста на верную дорогу именно в контексте GO, может какой-нибудь книгой (только не Эвансом)

2. Второй вопрос - каким образом правильно выделять разные типы ошибок, чтобы потом их можно было как-то использовать? Т.е. делить их по сервисам? Или типам операций внутри сервисов, например: ErrorAdd, ErrorUpdate.

Пока я выделил [ошибки по признакам REST](https://github.com/vitermakov/otusgo-hw/blob/hw12_calendar/hw12_13_14_15_calendar/pkg/utils/errx/errors.go) (логическа ошибка, не найдено, ошибка валидации), но их не внедрял.

### Запуск простого HTTP-сервера

Поковырял [http.server](https://github.com/vitermakov/otusgo-hw/blob/hw12_calendar/hw12_13_14_15_calendar/pkg/rest/server.go). Ввел пока встроенные мидлвары `authMiddleware`, `loggingMiddleware`. Для авторизации [сделал](https://github.com/vitermakov/otusgo-hw/blob/hw12_calendar/hw12_13_14_15_calendar/pkg/rest/http.go) структуру `AuthUser` и интерфейс `AuthService`. А также простую реализацию авторизации по имейлу в хедере Authorization.

### Юнит-тесты

Минимум сделал, но буду писать дальше

### Makefile

Почти ничего не менял, кроме расширения файла конфигурации

2022-12-22 06:07 UTC, dshemin requested changes

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +		if err = goose.Up(app.resources.DBPool, "migrations"); err != nil {
Важно:

Не стоит запускать миграции из приложения. В следующих задания мы будем оборачивать в docker образ и представьте: вы получаете докер образ с вашим приложением и запускаете в k8s с 3 репликами. Мы получим ситуацию когда три разных приложения начнут мигрировать одну и туже базу. Итог будет печальным.

Стоит разделять сервисные вещи от бизнес приложений.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +	stdlog.Println("closing resources")
Важно:

У нас же есть наш логер, почему мы тут используем стандартный?

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +	var err error
Важно:

Не надо объявлять переменные которые не нужны во всей функции, а только в нескольких блоках функции. Плюс, более читаемо, если мы будем объявлять их как можно ближе к тому месту где мы их используем.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +	wg.Add(1)
Важно:

Принято делать wg.Add перед той функцией, которую мы мы добавляем в wait группу.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +		defer func() {
Совет:

Нет нужды оборачивать в замыкание, можно просто `defer wg.Done()`.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/model/date_range.go
> +func alignDate(date time.Time, align DateAlign) time.Time {
Важно:

Что-то не доделано? Или забыли удалить ненужное?

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/model/event_test.go
> +		okTitle         = "okEvent"
Важно:

Скаляры лучше определять как константы.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/pgsql/event.go
> +	// Returning("uuid").To(&guid)
Совет:

Удалите пожалуйста этот не нужный комментарий

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/pgsql/event.go
> +	events, err := er.GetList(ctx, model.EventSearch{ID: &guid})
Важно:

Лучше зависти метод GeyByID или что-то типа такого. Выглядит странно текущее решение.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/pgsql/event.go
> +	if _, err := stmt.ExecAndClose(ctx, er.pool); err != nil {
Важно:

Можно просто:
```
_, err := stmt.ExecAndClose(...)
return err
```

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/pgsql/event.go
> +		event.ID, _ = uuid.Parse(dto.ID)
Критично:

А что если в базе лежит не валидный UUID? В боеом коде заглушать ошибки не следует никогда, исключение, если контракт заставляем вернуть ошибку, но она не в одном из ветвей логики не появляется.

Практика показывает, что закон Мёрфи работает.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/service/event.go
> +	if input.Date != nil || input.Duration != nil {
Важно:

Лучше сначала проверить негативный сценарий и вернуться чем порождать лишнюю вложенность.

Вот так более читаемо:

```
if input.Date == nil && input.Duration == nil {
    return nil   
}
...
```

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/utils/errx/errors.go
> +	/*
Совет:

Удалите пожалуйста лишний коментрий.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/utils/errx/errors.go
> +	TypeLogic   byte = 1 // логическая ошибка
Совет:

Воспользуйтесь `iota`

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +/*
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// } else {
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// fields, msg, args := l.getArgs(msgAndArgs)
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// fields, msg, args := l.getArgs(msgAndArgs)
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// } else {
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// fields, msg, args := l.getArgs(msgAndArgs)
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// } else {
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// fields, msg, args := l.getArgs(msgAndArgs)
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// } else {
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// fields, msg, args := l.getArgs(msgAndArgs)
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// } else {
Важно:

Пожалуйста удаляйте не нужные комментарии.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logger_test.go
> +	t.Run("wrong level", func(t *testing.T) {
Важно:

Одинаковые названия тестов! Учитывая код теста - тут должно быть другое название.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logger_test.go
> +		log.Fatal(err)
Важно:

Поломает тест такое решение. Вы используете testify, поэтому надо так:
```
file, err := os.CreateTemp(...)
require.NoError(t, err)
```

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logger_test.go
> +		require.True(t, errors.Is(err, ErrorOpenLogFile))
Совет:

`require.ErrorIs()`

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logger_test.go
> +		require.True(t, errors.Is(err, ErrorUnknownLevel))
Совет:

`require.ErrorIs()`

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/pkg/logger/logger.go
> +	if l == LevelNone {
Важно:

Лучше просто добавить `default` в `switch` и там вернуть ошибку чем так.

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/service/user.go
> +	return nil
Важно:

Просто `return us.repo.Delete(...)`

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/service/user.go
> +	if input.Email != nil {
Важно:

```
if input.Email == nil {
    return nil
}
...
```

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/service/event.go
> +	if err := es.repo.Delete(ctx, model.EventSearch{ID: &event.ID}); err != nil {
Важно:

`return es.repo.Delete(...)`

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/pgsql/user.go
> +	return nil
Важно:

```
_, err := stmt.ExecAndClose(...)
return err
```

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/pgsql/user.go
> +	if _, err := stmt.ExecAndClose(ctx, ur.pool); err != nil {
Важно:

```
_, err := stmt.ExecAndClose(...)
return err
```

2022-12-22 06:07 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/pgsql/user.go
> +	// Returning("uuid").To(&guid)
Совет:

Пожалуйста удалите комментарий.

2022-12-22 22:18 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/app/app.go
> +		if err = goose.Up(app.resources.DBPool, "migrations"); err != nil {
Пока не переделал, так как не понимаю как в Makefile прочитать конфигурауию для БД. Надо как-то прочитать конфиг на json? или эти параметры как переменные окружения будут приходить?

Пока удалил строки миграции и добавил строки установки и выполнения миграций 
migrate-install
migrate

2022-12-22 22:18 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/app/app.go
> +	stdlog.Println("closing resources")
ну там может быть вариант, что app.logger == nil, добавил проверку

2022-12-22 22:19 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/app/app.go
> +	var err error
убрал

2022-12-22 22:19 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/app/app.go
> +	wg.Add(1)
согласен, перенес

2022-12-22 22:19 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/app/app.go
> +		defer func() {
да, убрал

2022-12-22 22:19 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/model/date_range.go
> +func alignDate(date time.Time, align DateAlign) time.Time {
А, тут я не понял задачу. При получении событий на месяц/неделю/день нужно ли сначала выравнивать ее по первому дню месяца/недели или первой секунде дня.
Или просто к переданной дате добавлять промежуток (день-неделя-месяц) и их и использовать

2022-12-22 22:19 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/model/event_test.go
> +		okTitle         = "okEvent"
Даже для таких одноразовых случаев, тут же "okEvent" по сути не какая-то конкретная строка, а просто непустое значение? Или вы про emptyTitle, но как тогда я возьму адрес от константы

2022-12-22 22:19 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/repository/pgsql/event.go
> +	// Returning("uuid").To(&guid)
Удалил

2022-12-22 22:19 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/repository/pgsql/event.go
> +	events, err := er.GetList(ctx, model.EventSearch{ID: &guid})
Я постарался для выемки данных завести единый метод, в которую передавать модель поиска model.EventSearch. Например, могут быть добавлены опции, выбора конкретных полей или связей с выбираемой сущностью. Соответственно эти опции надо будет вводить во все сигнатуры GetBy..., внутри которых будут одинаковые действия обработки этих опций. 
Также нужно будет вынимать результат из БД через одинаковые DTO-шки.

А в таком решении есть одни ворота GetList. Но уже на уровне сервисов можно лепить и GetById и прочее.

2022-12-22 22:20 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/repository/pgsql/event.go
> +	if _, err := stmt.ExecAndClose(ctx, er.pool); err != nil {
поправил. У меня прямо к рукам пристал этот неверный шаблон :-)

2022-12-22 22:22 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/repository/pgsql/event.go
> +		event.ID, _ = uuid.Parse(dto.ID)
ну так этот репозиторий же конкретно под постгрес, где есть тип поля UUID, который не даст сохранить невалидный UUID. 
проверку добавил, но все получилось еще более запутано и получается теперь что если хотябы в одном месте будет ошибка не выдастся весь список.

Как вы бы поступили?

2022-12-22 22:22 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/service/event.go
> +	if input.Date != nil || input.Duration != nil {
Ну поставил, но вообще тут так не прокатит, если будут нужны еще какие-то проверки, так как условие 
```
if input.Date != nil || input.Duration != nil {
```
проверяет нужно ли вообще проверять дату, т.е. пытается ли пользователь сменить дату. Если добавится еще какая-то проверка не на дату, то логику придется вернуть.

2022-12-22 22:22 UTC, vitermakov commented on hw12_13_14_15_calendar/pkg/utils/errx/errors.go
> +	/*
убрал

2022-12-22 22:22 UTC, vitermakov commented on hw12_13_14_15_calendar/pkg/utils/errx/errors.go
> +	TypeLogic   byte = 1 // логическая ошибка
сделал

2022-12-22 22:22 UTC, vitermakov commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +/*
+

2022-12-22 22:22 UTC, vitermakov commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// } else {
+

2022-12-22 22:23 UTC, vitermakov commented on hw12_13_14_15_calendar/pkg/logger/logrus.go
> +	// } else {
убрал везде

2022-12-22 22:23 UTC, vitermakov commented on hw12_13_14_15_calendar/pkg/logger/logger_test.go
> +	t.Run("wrong level", func(t *testing.T) {
да, исправил

2022-12-22 22:23 UTC, vitermakov commented on hw12_13_14_15_calendar/pkg/logger/logger_test.go
> +		log.Fatal(err)
исправил, спасибо

2022-12-22 22:25 UTC, vitermakov commented on hw12_13_14_15_calendar/pkg/logger/logger_test.go
> +		require.True(t, errors.Is(err, ErrorOpenLogFile))
да, спасибо

2022-12-22 22:25 UTC, vitermakov commented on hw12_13_14_15_calendar/pkg/logger/logger_test.go
> +		require.True(t, errors.Is(err, ErrorUnknownLevel))
спасибо, мало практики еще тестов на го

2022-12-22 22:25 UTC, vitermakov commented on hw12_13_14_15_calendar/pkg/logger/logger.go
> +	if l == LevelNone {
поправил

2022-12-22 22:25 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/service/user.go
> +	return nil
пока сделаю так, а далее все зависит от Вашего ответа на вопрос про то как верно заворачивать ошибки.

2022-12-22 22:25 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/service/user.go
> +	if input.Email != nil {
сделал, но как я указывал ваше это работает только для одной проверки.

2022-12-22 22:25 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/service/event.go
> +	if err := es.repo.Delete(ctx, model.EventSearch{ID: &event.ID}); err != nil {
пока сделаю так, а далее все зависит от Вашего ответа на вопрос про то как верно заворачивать и классифицировать ошибки.

2022-12-22 22:25 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/repository/pgsql/user.go
> +	return nil
да

2022-12-22 22:26 UTC, vitermakov commented on hw12_13_14_15_calendar/internal/repository/pgsql/user.go
> +	if _, err := stmt.ExecAndClose(ctx, ur.pool); err != nil {
да

2022-12-23 01:14 UTC, dshemin approved these changes

2022-12-23 01:14 UTC, dshemin commented on hw12_13_14_15_calendar/internal/model/date_range.go
> +func alignDate(date time.Time, align DateAlign) time.Time {
Смотрите, чтобы получить данные за день - нам нужно: год, месяц и день.
Для недели, тут самый простой способ - день начала недели.
Для месяца - год и месяц.

Мы можем затребовать именно эти данные от пользователя, когда он вызывает наше АПИ. Сделать это можно двумя способами:

1. Прям указать поля: год, месяц, день для каждого запроса по необходимости.
2. Передать отметку времени или дату и от неё отсекать что-то.

Выбор на ваше усмотрение. Может быть у вас найдётся более интересное решение.

2022-12-23 01:14 UTC, dshemin commented on hw12_13_14_15_calendar/internal/model/event_test.go
> +		okTitle         = "okEvent"
Я про то, что у вас в блоке `var` смешаны и объявление переменных и определение констант.
Всё что можно, вынесите в блок `const` внутри функции.

2022-12-23 01:14 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/memory/event.go
> +	events = er.events
Совет:

Это не полноценная копия, есть нюансы https://go.dev/play/p/Ho_mUsaz6wr
Для полноценной копии надо использовать `copy`

2022-12-23 01:14 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/memory/user_test.go
> +		_ = userRepo.Update(ctx, model.UserUpdate{Email: &users[1].Email}, model.UserSearch{ID: &users[1].ID})
Важно:

Мы тестируем, поэтому желательно проверять ошибки. Ели не ожидаем их, то ставить `require.NoError` чтобы потом было легче разобраться почему тест упал.

2022-12-23 01:14 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/pgsql/event.go
> +	events, err := er.GetList(ctx, model.EventSearch{ID: &guid})
Задумка понятна, но не станет ли данный метод монструозным? Например, часто возникающая потребность, при получении списка отдавать только часть полей. Данное задание уже добавит лишний свойство в структуру model.EventSearch и усложнит выборку, read-model то в итоге будет разная. Потом добавим пагинацию, сортировку и фильтрацию по какому-нибудь полю. И мы получаем комбинаторный взрыв всех возможных сочетаний свойств. Тестировать потом такой метод будет крайне трудно.

Я пометил этот пункт как "Важно", за такие пункты я просто минусую баллы в категории "Понятность и чистота кода". На принятие проекта это не повлияет.

2022-12-23 01:14 UTC, dshemin commented on hw12_13_14_15_calendar/internal/repository/pgsql/event.go
> +	if _, err := stmt.ExecAndClose(ctx, er.pool); err != nil {
Шаблон отчасти верный, просто надо добавлять к ошибкам контекст:

```
if err := doSmth1(); err != nil {
    return fmt.Errorf("do smth1: %w", err)
}

if err := doSmth2(); err != nil {
    return fmt.Errorf("do smth2: %w", err)
}
return nil
```

А если не добавлять, то возвращать ошибку сразу.

2022-12-24 00:04 UTC, merged