Hw09 struct validator
vitermakov/otusgo-hw pull request #8
Opened 2022-12-09 00:15 UTC by vitermakov

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2022-12-09 07:02 UTC, dshemin requested changes

2022-12-09 07:02 UTC, dshemin commented on hw09_struct_validator/go.mod
> +module github.com/vitermakov/otusgo-hw/hw09structvalidator
Критично:

Не go gettable

2022-12-09 07:02 UTC, dshemin commented on hw09_struct_validator/validator/cmp_rule.go
> +		CmpFn: func(v float64, m float64) bool {
Совет:

Аргументы одинаковых типов, идущих подряд, можно не указывать. Например:
`func (v, m float64) bool`

2022-12-09 07:02 UTC, dshemin commented on hw09_struct_validator/validator/cmp_rule_test.go
> +			tc := tc
Важно:

Это надо делать до вызова t.Run().

2022-12-09 07:02 UTC, dshemin commented on hw09_struct_validator/validator/in_rule.go
> +		if kind >= reflect.Int && kind <= reflect.Int64 {
Совет:

Попробуйте описать это не через if'ы, а через switch

2022-12-09 07:02 UTC, dshemin commented on hw09_struct_validator/validator/in_rule.go
> +	for _, iv := range m.values {
Критично:

А что мы проверяем в этом цикле? Если честно - непонятно. Такое чувство что нам достаточно чтобы первый элемент массива имел нужный тип. но это неверно. Нам нужно чтобы все элементы массива имели нужный тип. Приэтом, либо числа, либо строки.

2022-12-09 07:02 UTC, dshemin commented on hw09_struct_validator/validator/len_rule.go
> +	if val.Kind() == reflect.String {
Совет:

Лучше сначала отсечь все негативные сценарии а потом уже рассмотреть позитивный. Проще читать код, когда там нет большой вложенности.

2022-12-09 07:02 UTC, dshemin commented on hw09_struct_validator/validator/rule.go
> +type Rule interface {
Совет:

В целом рабочий но переусложнённый интерфейс. Проще было бы: оставить тут только метод Check. А для инициализации рула - создать фабрику.

2022-12-09 07:02 UTC, dshemin commented on hw09_struct_validator/validator/validator.go
> +	fmt.Println(len(v))
Важно:

Скорее всего остаток отладки, надо убрать.

2022-12-09 07:02 UTC, dshemin commented on hw09_struct_validator/validator_test.go
> +	err := hw09structvalidator.Validate(nil)
Совет:

Если в тесте мы запускаем тестируемую функцию более одного раза - надо использовать табличные тесты.

2022-12-09 23:55 UTC, vitermakov commented on hw09_struct_validator/go.mod
> +module github.com/vitermakov/otusgo-hw/hw09structvalidator
Вы имеете в виду, что название пакета должно быть одинаковым с ссылкой hw09_struct_validator? Это не дают линтеры. Да и как я прочитал - это не мешает go get

2022-12-09 23:55 UTC, vitermakov commented on hw09_struct_validator/validator/cmp_rule.go
> +		CmpFn: func(v float64, m float64) bool {
Да, немного сокращает текcт, где нашел поправил

2022-12-09 23:56 UTC, vitermakov commented on hw09_struct_validator/validator/cmp_rule_test.go
> +			tc := tc
Конечно, ошибка, вынес из Run

2022-12-09 23:56 UTC, vitermakov commented on hw09_struct_validator/validator/in_rule.go
> +		if kind >= reflect.Int && kind <= reflect.Int64 {
Переделал в switch, странно, что линтер не ругнулся на ифы :-)

2022-12-09 23:59 UTC, vitermakov commented on hw09_struct_validator/validator/in_rule.go
> +	for _, iv := range m.values {
Тут мысль такая. По условию ДЗ, если поле структуры является массивом или слайсом, то при валидации к каждому элементу массива необходимо применить правило, которое указано в тегах и собрать оттуда ошибки. Это условие одинаково для всех типов правил и всех типов полей (в т.ч. типа структур или встроенных структур). Поэтому я эту логику решил вынести из чекеров правил и реализовать в процедуре валидации. 

```
hw09_struct_validator/validator/validator.go

	switch fVal.Kind() { //nolint:exhaustive // есть default
		case reflect.Slice, reflect.Array:
			rules, _ := ruleSet.(Rules)
			for i := 0; i < fVal.Len(); i++ {
				errorSet = append(errorSet, checkValue(fVal.Index(i), rules, append(names, strconv.Itoa(i))...)...)
			}

```

Т.е. в метод Check может попасть только значение скалярнго типа и я просто ищу его в массиве из Tag. 
Привидение к нужному типу значений массива m.values (это из тегов) идет в методе init.

Сравниваются значения, а не типы.

Для демонстрации того, что это работает добавил эти кейсы в тесты для строкового и целочисленного типов (UserRoles, Scores)

2022-12-09 23:59 UTC, vitermakov commented on hw09_struct_validator/validator/len_rule.go
> +	if val.Kind() == reflect.String {
Согласен, исправил

2022-12-09 23:59 UTC, vitermakov commented on hw09_struct_validator/validator/rule.go
> +type Rule interface {
Да, мне тоже он перестал нравиться. Убрал его из интерфейса, а инициализацию провожу через абстрактную фабрику.

2022-12-09 23:59 UTC, vitermakov commented on hw09_struct_validator/validator/validator.go
> +	fmt.Println(len(v))
Убрал

2022-12-10 00:00 UTC, vitermakov commented on hw09_struct_validator/validator_test.go
> +	err := hw09structvalidator.Validate(nil)
Переделал, но получилось больше кода. Из того файла перенес эти тесты в 
hw09_struct_validator/validator/validator_test.go в TestValidateInit. Там просто задублировался код.

2022-12-10 05:26 UTC, dshemin approved these changes

2022-12-10 05:26 UTC, dshemin commented on hw09_struct_validator/validator/cmp_rule.go
> +	if t >= reflect.Int && t <= reflect.Uint64 {
Совет:

Тут тоже можно переделать в switch, при этом вынести вызов m.CmpFn вне этого swicth так, как его вызов не зависит от `t`. От `t` зависит только значение `v`.

2022-12-10 05:26 UTC, dshemin commented on hw09_struct_validator/validator/in_rule.go
> +			v, err = strconv.ParseInt(arg, 10, 64)
Наверное тут вы хотели вызвать ParseUint?

2022-12-10 05:26 UTC, dshemin commented on hw09_struct_validator/validator/in_rule.go
> +	for _, iv := range m.values {
Окей, но зачем на пробегать по всему массиву?

Логика у нас тут получается такая:

1. Берём первый элемент.
2. Проверяем что он тот самый. Если это так, завершаемся. Иначе берём следующий элемент и проверяем его. 
3. Если не нашли то ошибка.

Так?

Теперь, рассмотри возможные варианты проверяемого массива:
1. []int {1, 2, 3}
2. []bool{true, false}
3. []interface{1, "2", "foo"}

Что будет в каждом из них?

2022-12-10 07:37 UTC, vitermakov commented on hw09_struct_validator/validator/in_rule.go
> +	for _, iv := range m.values {
```suggestion
	Окей, но зачем на пробегать по всему массиву?
```
Ну по заданию было собирать все ошибки, я и решил, что надо и все ошибки собрать в т.ч. и в массиве

```suggestion
	[]bool{true, false}
```
Задание ограничено было числовыми и строковыми типами

```suggestion
	[]interface{1, "2", "foo"}
```
Ну это последний удар, тут все рушится и надо хранить возможные значения в строках, а приведение к нужному типу в Check

2022-12-11 20:12 UTC, merged